name: Build image

# Note:
# HARBOR_URL, HARBOR_USERNAME, HARBOR_TOKEN are defined at the organization level

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_URL  }}
          username: ${{ vars.HARBOR_USERNAME  }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Read env file
        uses: cardinalby/export-env-action@v2
        id: readEnvFile 
        with:
          envFile: './docker/2.4.1rc7.env'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push (server)
        uses: docker/build-push-action@v5
        env:
          NVF_REPO=${{ env.NVF_REPO  }}
          NVF_VERSION=${{ env.NVF_VERSION }}
          NVF_BASE_IMAGE_SERVER=${{ env.NVF_BASE_IMAGE_SERVER }}
        with:
          context: ./docker
          push: true
          tags: ${{ vars.HARBOR_URL }}/ai4os/ai4-nvflare-server:${{ github.ref_name }}
          file: ./docker/Dockerfile-server

      - name: Build and push (client)
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ vars.HARBOR_URL }}/ai4os/ai4-nvflare-client:${{ github.ref_name }}
          file: ./docker/Dockerfile-client

      - name: Build and push (dashboard)
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ vars.HARBOR_URL }}/ai4os/ai4-nvflare-dashboard:${{ github.ref_name }}
          file: ./docker/Dockerfile-dashboard

